{
  try {
    helper("friggin' syntax error!");
    fail("Should have thrown an exception");
  }
 catch (  EvaluatorException e) {
  }
}
